name = "dnaoadfpm"
version = "0.1.0"
license = "MIT"
author = "Francisco Pe~nu~nuri"
maintainer = "frp7000@gmail.com"
description = "Dual numbers for arbitrary order automatic differentiation (FPM compatible)."

[build]
auto-executables = true
auto-tests = false

[preprocess]
[preprocess.cpp]

